name: verde_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # appnope is macOS specific, removing for Windows compatibility
  - bottleneck=1.4.2
  - contourpy=1.2.1
  - cycler=0.11.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - dill=0.3.8
  - fonttools=4.55.3
  - future=1.0.0
  - imageio=2.37.0
  - imageio-ffmpeg=0.6.0
  - ipykernel=6.29.5
  - ipympl=0.9.3
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - jupyterlab
  - kiwisolver=1.4.4
  - lmfit=1.3.3
  - matplotlib=3.9.2
  - numexpr=2.8.7
  - numpy=1.26.4
  - pandas=2.2.3
  - seaborn=0.13.2
  - tables=3.9.2
  - tqdm=4.67.1
  - uncertainties=3.2.2
  - pip
  - pip:
    - asteval==1.0.6
    - asttokens==2.0.5
    - stack-data==0.2.0
    - backcall==0.2.0
    - cython==3.0.11
    - emcee==3.1.6
    - emukit==0.4.11
    - gpy==1.13.2
    - pydoe==0.3.8
    - opencv-python